### ISSUE TITLE
色彩的存储方法最好也能配置

### ISSUE THREAD

**Issue by liushengqiang** [Shouheng88/Compressor#1]
色彩的存储方法最好也能配置：
public static final Bitmap.Config ALPHA_8
public static final Bitmap.Config ARGB_4444
public static final Bitmap.Config ARGB_8888
public static final Bitmap.Config RGB_565

**Comment by Shouheng88** [comment]
目前基于 Compressor 的压缩策略可以支持修改颜色，Luban 策略的因为本身没有创建 Bitmap（仅仅进行了采样和质量压缩），所以无法支持。现在这个需求已经开发和测试完毕，即将发布到 jCenter
