### ISSUE TITLE
原图尺寸比压缩预设尺寸小，压缩后的图片是压缩预设尺寸，不是原图尺寸

### ISSUE THREAD

**Issue by tomxukui** [Shouheng88/Compressor#11]
calculateRequiredWidth和calculateRequiredHeight的判断不太对

**Comment by Shouheng88** [comment]
能给出具体的代码吗

**Comment by tomxukui** [comment]
> 能给出具体的代码吗

Compressor类的calculateRequiredWidth方法

调用代码：
  Compress.with(Mapp.getInstance(), file)
                .setQuality(75)
                .setFormat(Bitmap.CompressFormat.JPEG)
                .strategy(Strategies.compressor())
                .setScaleMode(ScaleMode.SCALE_LARGER)
                .setMaxWidth(maxWidth)
                .setMaxHeight(maxHeight)
                .asBitmap()...

**Comment by Shouheng88** [comment]
是不是跟设置的 ScaleMode.SCALE_LARGER 边拉伸的模式有关系，你可以看下 [ScaleMode](https://github.com/Shouheng88/Compressor/blob/master/library/src/main/java/me/shouheng/compress/strategy/config/ScaleMode.java) 这个类的几个参数的含义

**Comment by tomxukui** [comment]
> 是不是跟设置的 ScaleMode.SCALE_LARGER 边拉伸的模式有关系，你可以看下 [ScaleMode](https://github.com/Shouheng88/Compressor/blob/master/library/src/main/java/me/shouheng/compress/strategy/config/ScaleMode.java) 这个类的几个参数的含义

不是ScaleMode的模式导致的，可能sdk定义的maxWidth和我设想的意思不同。我自己加了一些判断，解决了我自己的需求。

 /**
     * 压缩图片
     */
    public static void compressPhoto(File file, float maxWidth, float maxHeight, OnCompressPhotoListener listener) {
        //获取原图尺寸
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        options.inSampleSize = 1;
        BitmapFactory.decodeFile(file.getAbsolutePath(), options);
        int srcWidth = options.outWidth;
        int srcHeight = options.outHeight;

        Compress.with(Mapp.getInstance(), file)
                .setQuality(75)
                .setFormat(Bitmap.CompressFormat.JPEG)
                .strategy(Strategies.compressor())
                .setScaleMode(ScaleMode.SCALE_LARGER)
                .setMaxWidth(Math.min(srcWidth, maxWidth))
                .setMaxHeight(Math.min(srcHeight, maxHeight))
                .asBitmap()
                .setCompressListener(new RequestBuilder.Callback<Bitmap>() {

                    @Override
                    public void onStart() {
                    }

                    @Override
                    public void onSuccess(Bitmap bitmap) {
                        String base64 = Base64Util.bitmapToBase64(bitmap, Bitmap.CompressFormat.JPEG);

                        //回收Bitmap
                        if (bitmap != null && !bitmap.isRecycled()) {
                            bitmap.recycle();
                        }

                        if (listener != null) {
                            listener.result(new CompressPhoto(file.getAbsolutePath(), base64));
                        }
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        ToastUtil.showShort("压缩失败");
                    }

                })
                .launch();
    }

**Comment by Shouheng88** [comment]
能提供下具体的图片尺寸和设置的 maxWidth, maxHeight 的值吗

**Comment by tomxukui** [comment]
> 能提供下具体的图片尺寸和设置的 maxWidth, maxHeight 的值吗

比如:bitmap的宽和高都是320, maxWidth和maxHeight都是500, 最后压缩得到的图片的宽高都是500的

**Comment by Shouheng88** [comment]
你这么说的话我明白了，这种情况下确实会导致图片变成 500,500，我回头考虑下这种情况怎么处理比较合适

**Comment by Shouheng88** [comment]
现在已经支持了，可以通过调用 `setIgnoreIfSmaller()` 进行赋值，默认 true，也就是这种情况下直接忽略，不压缩
