### ISSUE TITLE
Android Q - Uri

### ISSUE THREAD

**Issue by ichenhe** [Shouheng88/Compressor#13]
Android Q 分区存储对于公共区域的图片只能拿到 Uri，进而拿到 `File descriptor`，不能获取 `File`。如果直接读取为 `Bitmap` 或 `bytes[]` 则违背了初衷可能导致 OOM。
请求添加对 `Uri` 或 `File descriptor` 或 `InputStream` 的支持。

**Comment by Shouheng88** [comment]
1.6.0 已支持，谢谢
