### ISSUE TITLE
华为手机上使用问题

### ISSUE THREAD

**Issue by tanguytq** [Shouheng88/Compressor#16]
在小米手机上使用没有任何问题，可以对图片进行压缩并保存在本地，但是在华为手机上测试时，发现本地没有保存压缩后的图片，测试了两款华为的手机，都是这样的情况，刚开始以为是图片过大的问题，但经过日志记录查看，发现大小没有任何问题，查看记录本地的日志，又发现压缩回调方法里，也没有任何错误信息，还返回成功，大佬，能帮忙解决这个问题吗

**Comment by Shouheng88** [comment]
提供下系统版本号吧，以及你是如何调用的，尽量给些具体的信息，不然无法排查问题

**Comment by tanguytq** [comment]
File tempFile = new File(path);
                    Compressor compressor = Compress.with(mContext, tempFile)
                        .setQuality(quality)
                        .setFormat(Bitmap.CompressFormat.JPEG)
                        .setTargetDir(cachePath)
                        .setCompressListener(new MeCompressListener())
                        .setCacheNameFactory(new MeCacheNameFactor(tempFile.getName()))
                        .strategy(Strategies.compressor())
                        .setMaxHeight(height)
                        .setMaxWidth(width)
                        .setScaleMode(ScaleMode.SCALE_SMALLER);
                    compressor.get();
private class MeCacheNameFactor implements CacheNameFactory
    {
        private String fileName;
        public MeCacheNameFactor(String fileName)
        {
            this.fileName = fileName;
        }

        @Override
        public String getFileName() {
            return fileName;
        }
    }

    private class MeCompressListener implements CompressListener
    {

        @Override
        public void onStart() {

        }

        @Override
        public void onSuccess(File result) {
            MyLog.d("Main", "压缩图片成功#######################");
        }

        @Override
        public void onError(Throwable throwable) {
            Log.d("Main", throwable.getMessage());
        }
    }
设备1：nova 6(5G)，型号 WLZ-AN00，版本号 10.0.1.173（C00E172R4P1）GPU Turbo，
EMUI版本 10.0.1，Android版本 10，处理器 HUAWEI Kirin 990
设备2：荣耀，型号TNY-AL00，Android 10，处理器 HUAWEI Kirin 990

**Comment by Shouheng88** [comment]
好的，明天给你看下哈

**Comment by tanguytq** [comment]
好的，谢谢，还有，我也使用过launch这个方法，结果报了"Failed to compress image, either caused by OOM or other problems."这个错误

**Comment by Shouheng88** [comment]
应该是文件写入过程出现的问题

- 你的小米手机的版本是多少？
- 进行压缩的时候设置的输出目录是多少？
- 另外，你可以看下你使用的库的版本，在 me.shouheng.compress.utils 包下面有个 Log 工具类，你可以通过这个类的静态方法开启 debug，这样就可以看出写入的时候具体报的是什么错了。

另外你觉得这个库对你有帮助的话，可以 star 一下哈～
