### ISSUE TITLE
依赖编译报错

### ISSUE THREAD

**Issue by lxn1445663013** [Shouheng88/Compressor#2]
![image](https://user-images.githubusercontent.com/23535332/57343150-bcd91880-7174-11e9-86da-4ef94590b988.png)

没有对Bitmap的直接压缩生成文件的方法吗？就是相机返回的流或者Bitmap直接压缩成文件，要不然还得存成文件再进行压缩增加了步骤，希望可以支持，谢谢！

**Comment by Shouheng88** [comment]
这个是某个资源没有链接到吧，你看下是不是缺少了某个资源

这个需求确实存在，过几天有空就加下

**Comment by lxn1445663013** [comment]
最好是直接对相机返回的流进行压缩这样就更方便了，直接down下来的也运行不了，我看看是不是少了什么





------------------ 原始邮件 ------------------
发件人: "WngShhng"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 上午9:48
收件人: "Shouheng88/Compressor"<Compressor@noreply.github.com>;
抄送: "令水剑客"<1445663013@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Shouheng88/Compressor] 依赖编译报错 (#2)




这个是某个资源没有链接到吧，你看下是不是缺少了某个资源
 
这个需求确实存在，过几天有空就加下
