### ISSUE TITLE
Publish To Maven Central

### ISSUE THREAD

**Issue by developernotes** [Shouheng88/Compressor#22]
Hi @Shouheng88,

Would you consider publishing to another repository instead of JCenter, possible Maven Central instead? The JCenter repository [became read-only on March 31, 2021](https://developer.android.com/studio/build/jcenter-migration). Android Studio has also started to provide a warning when using JCenter:

<img width="433" alt="Screen Shot 2021-06-11 at 15 38 55" src="https://user-images.githubusercontent.com/3225/121746212-24d45880-cacb-11eb-8886-22cfece5cb06.png">

Thanks!

**Comment by Shouheng88** [comment]
Done and the README file is updated.

**Comment by developernotes** [comment]
Hi @Shouheng88 

Perfect, thanks so much!
