### ISSUE TITLE
请问能指定图片的最大尺寸吗？

### ISSUE THREAD

**Issue by LLQQHH** [Shouheng88/Compressor#25]
比如maxSize=1M，而不是指定maxwidth，maxHeight，一般服务端都跟我说，你图片压缩到不超过1M就行了，他不会跟我说，你压缩到最大分辨率为1080X1920

**Comment by Shouheng88** [comment]
后面考虑下

**Comment by Shouheng88** [comment]
指定最大尺寸之后可以通过压缩大小和质量两个维度进行压缩，只强调大小可能会导致图片失真，不打算支持这种场景
