### ISSUE TITLE
1.5.0版本 通过 concrete设置最大宽高失效

### ISSUE THREAD

**Issue by zhu-xiaowei** [Shouheng88/Compressor#26]
.concrete {
            this.config = Bitmap.Config.RGB_565
            this.maxWidth = 4000f
            this.maxHeight = 4000f
            this.scaleMode = ScaleMode.SCALE_LARGER
}.launch()
看了下源码没有设置宽度：
![](https://img.carlwe.com/xs/compressor_error.png)

**Comment by Shouheng88** [comment]
晚点修复

**Comment by Shouheng88** [comment]
1.6.0 已修复，谢谢！
