### ISSUE TITLE
请问如何控制压缩的图片在50~100k?

### ISSUE THREAD

**Issue by shuijianbaozi** [Shouheng88/Compressor#7]
博主,首先感谢分享开源你的代码,其中有几个属性很奇怪,我不确定是我用的问题,还是怎么回事,Quality在0-100之间,请问该怎么解读,如题,如果我想控制图片在50~100k之间要怎么处理合适?

**Comment by Shouheng88** [comment]
图片压缩的时候有个图片质量，上面的那个0～100的取值指的是图片质量。对于图片大小的控制，现在还不支持的。如果你有这个需求的话，可以参考下这个代码[ImageUtils](https://github.com/Shouheng88/AndroidUtils/blob/master/utils/src/main/java/me/shouheng/utils/ui/ImageUtils.java)

**Comment by jp1017** [comment]
> 可以参考下这个代码[ImageUtils](https://github.com/Shouheng88/AndroidUtils/blob/master/utils/src/main/java/me/shouheng/utils/ui/ImageUtils.java)

Page not found

**Comment by Shouheng88** [comment]
https://github.com/Shouheng88/Android-utils 中的 ImageUtils
链接：https://github.com/Shouheng88/Android-utils/blob/master/utils/src/main/java/me/shouheng/utils/ui/ImageUtils.java
